### ISSUE TITLE
Great script but unable to get started in automatic startup

### ISSUE THREAD

**Issue by jremi** [respeecher/micmixer#1]
I want to thank you for this great script.

I hope you can help me. Im using Ubuntu 19.10 x64. 

My `/etc/rc.local` is setup to spawn a shell script which then invokes your `micmixer.sh`.

The issue is that I can only make your micmixer register the sinks when I execute the shell script from directly within the system terminal. If I attempt to spawn the script via for example `/etc/rc.local` it will almost never run. Its the most unusual issue. 

Any ideas how to get the sinks to automatically add to the system on system boot. I'm starting the pulseaudio like this...

```
systemctl --user enable pulseaudio
systemctl --user start pulseaudio
/home/myuser/respeecher/mixmixer.sh
```

When I do this from the startup it almost never makes the sinks appear. I don't see any errors either. It looks like it loads but when I run...

```
pactl list short sinks
```

I dont seem them. Note: the micmixer.sh is already set for `chmod +x` ... The script does load but I simply dont get the sinks added. I also have made sure that my user is added to the /etc/group `audio, pulse, pulse-access`

When I run micmixer.sh from shell after it boots manually it loads them fine.

The crazy part is that if I run it via the automatic rc.local script ... occasionally it will actually register the sinks. Its intermittent.

Any help greatly appreciated! Thanks again for this script.

🙏

**Comment by jremi** [comment]
It appears that the micmixer script when i loaded at startup was sometimes having a fight with the pulseaudio system config. 
I ended up taking the most important parts of the micmixer.sh ...

load-module/set-default-sink/set-default-source commands being used with pacmd in the script and moved them directly into my ~/.config/pulse/default.pa... Now when my system boots it just runs the commands directly from the user level pulseaudio default.pa config file. This seems to have cleared everything up.

Thank you!

**Comment by belevtsoff** [comment]
Hi @jremi. Glad you found it useful! Sorry I got here so late, but basically adding things to ```default.pa``` seems like a proper solution. One way we could automate this is by adding an option to the script to dump the changes to a file instead of applying them at runtime. I'll try to look into it this week
